In [16]:
pip install pandas

Requirement already satisfied: pandas in C:\Users\surfce\AppData\Roaming\Python\Python314\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\surfce\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\surfce\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\surfce\AppData\Roaming\Python\Python314\site-packages (from pandas) (2026.4)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\surfce\AppData\Roaming\Python\Python314\site-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in C:\Users\surfce\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [17]:
import pandas as pd

In [18]:
data=pd.read_csv(r"C:\Users\surfce\Downloads\house_prices_practice.csv")

In [19]:
data.head()

,Id,OverallQual,GrLivArea,GarageCars,TotalBsmtSF,YearBuilt,FullBath,BedroomAbvGr,LotArea,SalePrice
0,1,7,1560,0,1658,1969,2,1,8059,177106
1,2,4,2827,2,1319,2012,3,4,13530,301044
2,3,8,3920,0,841,2010,1,4,9010,360609
3,4,5,3044,0,1058,1998,0,4,13207,240556
4,5,7,801,1,2428,2020,0,1,9117,193656

In [20]:
data.tail()

,Id,OverallQual,GrLivArea,GarageCars,TotalBsmtSF,YearBuilt,FullBath,BedroomAbvGr,LotArea,SalePrice
295,296,1,3495,1,1792,1954,2,5,4978,250604
296,297,5,3438,3,1266,2003,0,1,9373,329906
297,298,6,1992,0,1148,1996,1,1,7907,184623
298,299,3,3722,1,1407,1998,1,1,8097,303345
299,300,9,1667,0,988,1958,2,1,14553,204982

In [21]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            300 non-null    int64
 1   OverallQual   300 non-null    int64
 2   GrLivArea     300 non-null    int64
 3   GarageCars    300 non-null    int64
 4   TotalBsmtSF   300 non-null    int64
 5   YearBuilt     300 non-null    int64
 6   FullBath      300 non-null    int64
 7   BedroomAbvGr  300 non-null    int64
 8   LotArea       300 non-null    int64
 9   SalePrice     300 non-null    int64
dtypes: int64(10)
memory usage: 23.6 KB

In [22]:
data.describe()

,Id,OverallQual,GrLivArea,GarageCars,TotalBsmtSF,YearBuilt,FullBath,BedroomAbvGr,LotArea,SalePrice
count,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000
mean,150.500000,5.326667,2307.386667,1.330000,1468.796667,1986.163333,1.523333,2.926667,8969.453333,252262.903333
std,86.746758,2.873001,1042.561303,1.109898,672.333705,21.377089,1.131543,1.456604,3753.531132,74998.055214
min,1.000000,1.000000,504.000000,0.000000,303.000000,1950.000000,0.000000,1.000000,2009.000000,82494.000000
25%,75.750000,3.000000,1392.250000,0.000000,903.000000,1967.000000,0.000000,2.000000,5996.250000,190355.250000
50%,150.500000,5.000000,2265.500000,1.000000,1502.000000,1986.000000,2.000000,3.000000,9031.000000,251292.500000
75%,225.250000,8.000000,3306.500000,2.000000,2129.500000,2004.250000,3.000000,4.000000,12316.000000,307105.000000
max,300.000000,10.000000,3998.000000,3.000000,2492.000000,2023.000000,3.000000,5.000000,14987.000000,435291.000000

In [23]:
data.shape

(300, 10)

In [24]:
data.columns

Index(['Id', 'OverallQual', 'GrLivArea', 'GarageCars', 'TotalBsmtSF',
       'YearBuilt', 'FullBath', 'BedroomAbvGr', 'LotArea', 'SalePrice'],
      dtype='object')

In [25]:
data.dtypes

Id              int64
OverallQual     int64
GrLivArea       int64
GarageCars      int64
TotalBsmtSF     int64
YearBuilt       int64
FullBath        int64
BedroomAbvGr    int64
LotArea         int64
SalePrice       int64
dtype: object

In [26]:
data.isnull().sum()

Id              0
OverallQual     0
GrLivArea       0
GarageCars      0
TotalBsmtSF     0
YearBuilt       0
FullBath        0
BedroomAbvGr    0
LotArea         0
SalePrice       0
dtype: int64

In [27]:
int(data.duplicated().sum())

0

In [28]:
data.drop_duplicates(inplace=True)

In [29]:
data.nunique()

Id              300
OverallQual      10
GrLivArea       287
GarageCars        4
TotalBsmtSF     278
YearBuilt        73
FullBath          4
BedroomAbvGr      5
LotArea         296
SalePrice       300
dtype: int64

In [32]:
x=data[['OverallQual','GrLivArea','GarageCars','TotalBsmtSF',
        'YearBuilt','FullBath','BedroomAbvGr','LotArea']]
y=data[['SalePrice']]
print(x)
print(y)

     OverallQual  GrLivArea  GarageCars  TotalBsmtSF  YearBuilt  FullBath  \
0              7       1560           0         1658       1969         2
1              4       2827           2         1319       2012         3
2              8       3920           0          841       2010         1
3              5       3044           0         1058       1998         0
4              7        801           1         2428       2020         0
..           ...        ...         ...          ...        ...       ...
295            1       3495           1         1792       1954         2
296            5       3438           3         1266       2003         0
297            6       1992           0         1148       1996         1
298            3       3722           1         1407       1998         1
299            9       1667           0          988       1958         2

     BedroomAbvGr  LotArea
0               1     8059
1               4    13530
2               4     9010
3               4    13207
4               1     9117
..            ...      ...
295             5     4978
296             1     9373
297             1     7907
298             1     8097
299             1    14553

[300 rows x 8 columns]
     SalePrice
0       177106
1       301044
2       360609
3       240556
4       193656
..         ...
295     250604
296     329906
297     184623
298     303345
299     204982

[300 rows x 1 columns]

In [33]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2, random_state=12)

In [34]:
from sklearn.linear_model import LinearRegression
slr=LinearRegression()
slr.fit(x_train,y_train)
slr.predict(x_test)

array([[322282.5431834 ],
       [385458.15265493],
       [207237.33477461],
       [330855.22338302],
       [121908.96253398],
       [375108.10558674],
       [314546.53143914],
       [208021.40165097],
       [195653.48014182],
       [263678.98794911],
       [301812.54037438],
       [193196.30280169],
       [288125.8293911 ],
       [287327.13221277],
       [279901.60413633],
       [259500.11596118],
       [244544.14681399],
       [ 92726.42536953],
       [195930.78396675],
       [380829.69796294],
       [186627.69311551],
       [226935.83169137],
       [236240.71994047],
       [163129.99885131],
       [253733.72020922],
       [251503.62688526],
       [209578.9074317 ],
       [330829.30525549],
       [174989.22697722],
       [165515.57350818],
       [169754.92556337],
       [219836.21560033],
       [242926.15981885],
       [219144.61969513],
       [395918.92166136],
       [252044.24341115],
       [280225.93086959],
       [378973.90634702],
       [148145.86406382],
       [317629.90704935],
       [302248.44565522],
       [143897.85285476],
       [169141.58142888],
       [315231.93304144],
       [216759.68204755],
       [297999.35376512],
       [257229.93545587],
       [244289.26222301],
       [340693.30193849],
       [368655.09251521],
       [194289.10836118],
       [269220.63257097],
       [192068.90251095],
       [210628.44545573],
       [292775.83192997],
       [115431.99476816],
       [206191.59940719],
       [282692.11991387],
       [118876.94713104],
       [169476.9318799 ]])

In [36]:
x=data[['OverallQual','GrLivArea','GarageCars','TotalBsmtSF',
         'YearBuilt','FullBath','BedroomAbvGr','LotArea']]
y=data[['SalePrice']]
print(x)
print(y)

     OverallQual  GrLivArea  GarageCars  TotalBsmtSF  YearBuilt  FullBath  \
0              7       1560           0         1658       1969         2
1              4       2827           2         1319       2012         3
2              8       3920           0          841       2010         1
3              5       3044           0         1058       1998         0
4              7        801           1         2428       2020         0
..           ...        ...         ...          ...        ...       ...
295            1       3495           1         1792       1954         2
296            5       3438           3         1266       2003         0
297            6       1992           0         1148       1996         1
298            3       3722           1         1407       1998         1
299            9       1667           0          988       1958         2

     BedroomAbvGr  LotArea
0               1     8059
1               4    13530
2               4     9010
3               4    13207
4               1     9117
..            ...      ...
295             5     4978
296             1     9373
297             1     7907
298             1     8097
299             1    14553

[300 rows x 8 columns]
     SalePrice
0       177106
1       301044
2       360609
3       240556
4       193656
..         ...
295     250604
296     329906
297     184623
298     303345
299     204982

[300 rows x 1 columns]

In [37]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2, random_state=12)

In [38]:
from sklearn.linear_model import LinearRegression
slr=LinearRegression()
slr.fit(x_train,y_train)#Model Training
slr.predict(x_test) #model testing

array([[322282.5431834 ],
       [385458.15265493],
       [207237.33477461],
       [330855.22338302],
       [121908.96253398],
       [375108.10558674],
       [314546.53143914],
       [208021.40165097],
       [195653.48014182],
       [263678.98794911],
       [301812.54037438],
       [193196.30280169],
       [288125.8293911 ],
       [287327.13221277],
       [279901.60413633],
       [259500.11596118],
       [244544.14681399],
       [ 92726.42536953],
       [195930.78396675],
       [380829.69796294],
       [186627.69311551],
       [226935.83169137],
       [236240.71994047],
       [163129.99885131],
       [253733.72020922],
       [251503.62688526],
       [209578.9074317 ],
       [330829.30525549],
       [174989.22697722],
       [165515.57350818],
       [169754.92556337],
       [219836.21560033],
       [242926.15981885],
       [219144.61969513],
       [395918.92166136],
       [252044.24341115],
       [280225.93086959],
       [378973.90634702],
       [148145.86406382],
       [317629.90704935],
       [302248.44565522],
       [143897.85285476],
       [169141.58142888],
       [315231.93304144],
       [216759.68204755],
       [297999.35376512],
       [257229.93545587],
       [244289.26222301],
       [340693.30193849],
       [368655.09251521],
       [194289.10836118],
       [269220.63257097],
       [192068.90251095],
       [210628.44545573],
       [292775.83192997],
       [115431.99476816],
       [206191.59940719],
       [282692.11991387],
       [118876.94713104],
       [169476.9318799 ]])

In [39]:
from  sklearn.metrics import r2_score
y_pred=slr.predict(x_test)
r2=r2_score(y_test,y_pred)
print(r2)

0.9776064358983928